# Generated by Django 3.1.2 on 2020-11-07 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IntFactorization', '0002_userhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnapsackHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knapsack_answer', models.FloatField()),
                ('knapsack_input', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrimeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prime_answer', models.CharField(max_length=9999)),
                ('prime_input', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='useracc',
            name='email',
        ),
        migrations.AlterField(
            model_name='useracc',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserHistory',
        ),
        migrations.AddField(
            model_name='primehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntFactorization.useracc'),
        ),
        migrations.AddField(
            model_name='knapsackhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntFactorization.useracc'),
        ),
    ]
