# Generated by Django 3.1.2 on 2020-11-07 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IntFactorization', '0003_auto_20201107_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
