# Generated by Django 3.1.2 on 2020-11-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntFactorization', '0005_auto_20201107_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knapsackhistory',
            name='knapsack_answer',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='knapsackhistory',
            name='knapsack_input',
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='primehistory',
            name='prime_answer',
            field=models.CharField(max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='primehistory',
            name='prime_input',
            field=models.IntegerField(blank=True),
        ),
    ]
