# Generated by Django 3.1.2 on 2020-11-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntFactorization', '0006_auto_20201115_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='knapsackhistory',
            name='knapsack_limit',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
