# Generated by Django 3.1.2 on 2020-11-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntFactorization', '0007_knapsackhistory_knapsack_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='primehistory',
            name='prime_status',
            field=models.CharField(max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='knapsackhistory',
            name='knapsack_input',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
