# Generated by Django 3.1.2 on 2020-11-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntFactorization', '0008_auto_20201121_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primehistory',
            name='prime_input',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
